version: '3.9'

services:
    
    muzero-notebook:
        build:
            context: .
        container_name: muzero-notebook
        ports: 
            - 8889:8889
            - 6006:6006
        runtime: nvidia
        volumes:
            - .:/work
    
